### ISSUE TITLE
Decide on features for minimal viable product

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#150]
# MVP features
## Already working
- [x] Nested hierarchy of concepts #139 
- [x] Comparison table #103
- [x] Selection by autocomplete/typeahead
- [x]  Selection by overlapping #135 
- [x] Sort of overlapping by precision, recall, total concepts, shared concepts #158
- [x] Configurable "Cards" showing concept set information 
## Not yet working -- planned for MVP no matter what
- [x] #116 
- [ ] #161
- [x] #162
- [x] #167
## Net yet working -- planned for MVP but blocked and waiting for Palantir, etc.
- [x] Ability to add/remove concepts from concept sets (Kim Murray request) #147 
  - [ ] #153
- [x] #117
## On deck after MVP
- [ ] #121 
- [ ] Visualization #123 
- [ ] Additional cset and concept data display (names of creator, reviewer, etc.; project links; links to cset on concept set browser...) #146 #143

**Comment by hugwuoke** [comment]
I went through the issues and closed those which seemed completed. This organization might still be useful but I believe we are further than a minimally viable product.

**Comment by joeflack4** [comment]
Yep! I am gonna go ahead and close this one. There are still some linked issues that haven't been completed, but I don't think this issue makes sense any more as a milestone or grouping issue.
