### ISSUE TITLE
Download /refresh: tables using object ontology api (e.g. full concept set info from enclave)

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#189]
## Overview
Joe just recently changed `initialize()` so that the database refresh can happen using `full_data_refresh.py`. It was going to have a GitHub action next. We still could do that, but it may not be necessary, as we can can fetch newer updates faster using the objects API.

## Sub-task list
- [x] 1. `manage` table & its logic
- [x] 2. First case: `OmopConceptSet`
- [x] 3. List of objects to refresh
- [x] 4. GitHub action using cronjob
- [ ] 5. Fetch on requests as well?
- [x] 6. Additional `manage` table features

### 1. `manage` table
**Table**
For now, this should be a key/value table (two cols). It should have 1 row for each table that needs to be updated, e.g. `concept_set_members__last_updated` in the `key` column, and a datetime, e.g. `%Y-%m-%d %H:%M:%S` in the `value` column.

**Logic**
The `objects_api.py` already has a lot of what we need for this. We want to [query](https://www.palantir.com/docs/foundry/api/ontology-resources/objects/search/) using `gt` for 'greater than' on the `created_at` (or it might be `createdAt` property). 

### 2. First case: [`OmopConceptSet`](https://unite.nih.gov/workspace/ontology/object-type/omop-concept-set/properties)
See what comes back from the API and share with Siggie before continuing further.

### 3. List of objects to refresh
For concept sets, we need single versions or most recent versions. then concept set expressions for them, then containers for them. Then the linked concepts. other things linked to it.

`objectName` -> `table_name`: List of objects to refresh and the corresponding tables they impact :
- [x] `OmopConceptSet` -> `omopconceptset `
- [x] `Researcher`? -> `researcher`

### 4. GitHub action using cronjob
Try refreshing hourly.

### 5. Fetch on requests as well?
Once an hour might not be enough, i.e. a user does something and we want to show the update immediately. We may want to parse quests and see what objects they are affecting, and do a refresh when the user either (i) asks for it specifically, like if we add a 'refresh' button, or (ii) makes a push that affects some object(s).

### 6. Additional `manage` table features
Some fields we're thinking about adding to the  `manage` table:
- [x] `n_last_refresh` (`int`): Shows the number of rows/objects we got back in the last refresh.
- [x] `refresh_status` (`str` / `factor`). The status of the refresh, so we don't start refreshing a table if it's already refreshing. E.g.: `done`, `in-progress`

### Resources
- [OmopConceptSet object definition](https://unite.nih.gov/workspace/ontology/object-type/omop-concept-set/properties)
- [objects search docs](https://www.palantir.com/docs/foundry/api/ontology-resources/objects/search/).

**Comment by Sigfried** [comment]
I thought this was already an issue, but I can't find it.

**Comment by joeflack4** [comment]
@Sigfried Should be addressed by https://github.com/jhu-bids/TermHub/commit/208b189a6e24c40933c271c2300941c6387529f8

**Comment by joeflack4** [comment]
@Sigfried I think this has been more or less fully addressed. Feel free to create a new issue if you think it's worth tracking any additional updates we want to do to db refreshing.
