### ISSUE TITLE
Grouping issue: testing

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#222]
## Overview
We need to increase TermHub's stability. CC @Sigfried @Leskena2 

## Sub-task list
- [ ] 1. Automated: Come up with a list of things that do not yet have unit tests but should.
- [ ] 2. Automated: Write unit tests
- [ ] 3. Manual: Come up with some scenarios to have users tests
- [ ] 4. Manual: Schedule and have some users do those tests

### How to run tests
a. PyCharm
You'll see a "Play" button in the sidebar. You can click that to run then. I recommend running using the debugger.
<img width="442" alt="Screen Shot 2023-05-24 at 5 46 22 PM" src="https://github.com/jhu-bids/TermHub/assets/13045020/37936a28-3554-416b-988b-cc910d71b0db">

b. CLI (examples)
run all unit tests (will fail currently, because not all tests currently pass)
  `python -m unittest discover`
run all tests in a module (will fail currently)
  `python test/test_enclave_wrangler.py`
run single test in a module
  `python -m unittest test.test_backend.TestBackend.test_counts_over_time`

**Comment by joeflack4** [comment]
Closing this as redundant with #353
