### ISSUE TITLE
DB refresh: GitHub actions: Bugs & major tasks

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#237]
## Overview
The action is still not working. Keep cracking at it.

## Sub-tasks
- [x] 1. _Via datasets API_: Fix any bugs preventing action from finishing
- [x] 2. _Via datasets API_: Why, when it fails, does `n3c` schema become affected? it is only supposed to be backed up when the script has finished, and not touched otherwise.
- [ ] 3. _Via objects API_: When script finished, create an action to use it.

**Comment by joeflack4** [comment]
Solved this problem today: git submodule
https://github.com/jhu-bids/TermHub/actions/runs/4069912369/jobs/7010160430

Need to fix a bug where the action does not initialize git submodules in order to work w/ the download data.

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/TermHub/TermHub/backend/db/../../termhub-csets/datasets/prepped_files/code_sets.csv'
```

If git submodules are tricky for the action, we could potentially do this in TermHub's directory, outside of the submodule(s).

**Comment by joeflack4** [comment]
Solved problem today with parquet memory issue by chunking this operation.

**Comment by joeflack4** [comment]
New problem is this: https://github.com/jhu-bids/TermHub/actions/runs/4229442974/jobs/7345822395
```
  File "/Users/runner/work/TermHub/TermHub/backend/db/../../backend/db/load.py", line 80, in indexes_and_derived_tables
    if last_successful_step >= step_num:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```
easy fix

**Comment by joeflack4** [comment]
Held up now by:
- #258

**Comment by joeflack4** [comment]
Closing this issue as now redundant with #259 and #260.

The "DB refresh via the datasets API" (AKA now also called "DB reset") was actually fixed in late March. The issue was that some of the code we had written previously to read CSVs was written like `{table}` instead of `{schema}.{table}`, so it was touching the wrong schema.
