### ISSUE TITLE
User testing based todo's

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#278]
## Overview
Various users gave us feedback. Here's what we need to fix.

## Sub-task list
- [ ] 1. Need more screen space
- [ ] 2. 

## User feedback collected
- [ ] AndreaZ (hasn't tested as of 2023/03/15)
- [ ] EileenK
- [ ] RichardZ
- [ ] CRoeder
- [ ] LisaE
- [ ] Kim (hasn't tested as of 2023/03/15)
- [ ] BryanL (hasn't tested as of 2023/03/15)

## Additional info
- Feedback spreadsheet: https://docs.google.com/spreadsheets/d/1aMsGwV6JkWSMpaEwF4d7ne7aBLr2p-s_dRBWgjeHG3U/edit#gid=880790843
- Eileen's feedback issue: https://github.com/jhu-bids/TermHub/issues/275

**Comment by Sigfried** [comment]
@joeflack4, it used to be if you hover over a sub-task, github gave an icon to allow turning it into a separate issue. I'm not seeing that anymore (at least not on this issue.) Do you know why?

**Comment by joeflack4** [comment]
@Sigfried Hey Siggie. This functionality is working on my end. Maybe a browser issue on your end? Maybe clear cache and log out / back in?

<img width="1257" alt="Screen Shot 2023-04-07 at 3 22 10 PM" src="https://user-images.githubusercontent.com/13045020/230665533-d1023338-25ed-4e4b-8ff1-7227bf5137bd.png">
