### ISSUE TITLE
Set up Hope's dev environment

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#305]
## Overview
Set up Hope's development environment for working on TermHub.

## Sub-tasks
- [ ] 1. Set up IDE (e.g. VSCode)
- [ ] 2. Ensure can run the backend
- [ ] 3. Ensure can run the frontend
- [ ] 4. Ensure can push to GitHub

**Comment by joeflack4** [comment]
Welcome @hugwuoke! @Fabiofdez Here are some things Hope will need if you can assist! @Sigfried Feel freet o add to this list if I forgot anything.

**Comment by joeflack4** [comment]
Thanks for helping, @Fabiofdez! Were you guys able to complete sub-steps (1) through (4) in the OP, or just some of them?

**Comment by Fabiofdez** [comment]
Yes I was able to get her vscode and frontend/backend set up, though we didn't get the chance to test git push/pull, I can go over that with her next week.
