### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#356]
## Overview
Update the way we do versioning, and increment version number.

## Sub-tasks
- [x] Create a `frontend/version.js` file
    - Changed to `frontend/src/version.js` (Matthew Jo)
- [x] Make a variable for the version and set it to `'0.2.0'`
- [x] Import that into `AboutPage.js` and update the header (currently `<h1>Welcome to TermHub! Beta version 0.1</h1>`) so that it uses the variable
- [x] Also make it so that the header (currently says **TermHub Version 0.1**) also uses that version variable
- [x] Make a new git tag. I think this will work: `git tag 0.2.0; git push --tags`

## Future ideas
- [ ] Automated way to create the version (does the tag and updates the variable at the same time)

**Comment by mtj0712** [comment]
Relative imports outside of src/ are not supported, so I will put `version.js` inside `frontend/src/` directory.

**Comment by joeflack4** [comment]
@mtj0712 Thanks for solving that, Matt! My bad, I meant to say `frontend/src/` earlier
