### ISSUE TITLE
DB refresh button

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#357]
## Overview
I'm currently wrapping up work on a feature that will automatically refresh the database with data every day. It will do this via a GitHub action. However, some of our users have requested data more frequently. For now, the next easiest thing to do will be to give them a button that they can click which will call the GitHub action to trigger the refresh.

If you could make a new branch off of `develop` and open up a pull request for this work, that'd be great!

## Sub-tasks
- [x] 1. Add a 'Database refresh' section to the 'Help / About' page @forbeskat 
- [x] 2. Add a button to that section @forbeskat 
- [ ] 3. Simplified button logic @forbeskat 
- [ ] 4. Backend logic / tokens when GitHub action is ready @joeflack4 

### 3. Simplified button logic
Write some logic to call the GitHub action when button is clicked. I haven't yet set up the action so that it can receive triggers like this yet, so the code we write will just be kind of a placeholder. But I think next week we can finish it up.

_edit_: 
I just changed this section (previously called "initial button logic"). I did some research and basically the only way to avoid exposing our GitHub token is to move this logic to the backend. So all you need to do is make a call to a backend route which I will create in step (4). I'm just gonna call it `/db-refresh`.

I was gonna refer you to `UploadCsv.js`, but that button has a lot more stuff that you don't need. What you need will mostly look something like:

```js
const handleClick = () => {
      axiosPost('db-refresh', {})
}

<button onClick={handleClick}>Trigger Workflow</button>
```

If you are feeling confident in Python you can add this to `app.py` as well, then restart your backend server and see if clicking the button causes this to print in the backend console. But I'm planning and adding this and flesh it out with the logic that calls the GitHub action next week.
```py
@APP.get("/db-refresh")
def db_refresh_route()
    print("to be implemented")
```

**Comment by joeflack4** [comment]
@Sigfried I have another idea. Let's do this button first, but after it is working, we should move this GitHub action calling logic to a separate function outside of the button component, and we should call it whenever we do certain things, such as (i) user edits and concept set(s) and pushes those changes to the enclave, (ii) user uses CSV upload.

I plan to write logic on the backend so that if the refresh is currently running, a subsequent push will not interrupt it, and will instead trigger another run after the initial run completes, if necessary.

**Comment by joeflack4** [comment]
@forbeskat I figured out what to put in `event_type` and I added it to the snippet. It should be set to `'refresh-db'`.  The `client_payload` part is not needed, but we can keep it to allow future customization. If we get an error saying "unrecognized payload" or something, then I think we can just remove it.
