### ISSUE TITLE
Test subgraph function and endpoint

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#365]
Test function: `subgraph([1738170, 1738171, 1738202, 1738203])`
Test endpoint: `http://127.0.0.1:8000/subgraph/?id=1738170&id=1738171&id=1738202&id=1738203`

Should return 

    [
      [
        "1738170",
        "1738171"
      ],
      [
        "1738170",
        "1738202"
      ],
      [
        "1738170",
        "1738203"
      ]
    ]

**TODO:**
 - [x] More complex structure (polyhierarchy)
 - [x] Example that requires finding common ancestors to connect disconnected subgraph components
 - [x] Example that requires filling in gaps where, for instance, a parent node and grandchild node appear in the requested node list, but not the child that connects them.
 - [ ] Example also include two subgraph components that don't have any common ancestors (optional).

**Comment by hugwuoke** [comment]
@Sigfried the last box on the issue description I was never really confident that I had something that met the criteria. I don't think we talked about that much yesterday so I was wondering if that is still something that you would like to add for the test_subgraph function.
