### ISSUE TITLE
Editing cset: create new column

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#383]
## Overview
Rather than editing a concept set in place, it should create a new column copied from the one clicked, so it's more obvious what exact changes have been made. Have that column appear before or after all the other concept set columns. Highlight it in some way.

## Sub-task list
- [ ] 1. Editing cset: create new column
- [ ] 2. Put edited columns to left or right
- [ ] 3. Highlight edited columns

**Comment by joeflack4** [comment]
@Sigfried I created a simpler title and put what you'd written inside the issue body.
