### ISSUE TITLE
Download indented csv of displayed concepts

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#390]
## Overview
New feature, to help SMEs in particular. We need to "print" out a hierarchy displayed on TermHub and download i as a CSV of displayed concepts. Hierarchy should be represented with indents.

## Sub-tasks
- [x] 1. Have a button that downloads a CSV of indented concepts
- [x] 2. Please move counts to after the last level, followed by vocabulary
- [x] 3. Have the counts be in the same order as in the TermHub page
- [x] 4. 3 last new empty columns: Include, Exclude, Notes
- [x] 5. Give more room to the download button

### Is your feature request related to a problem? Please describe.
"Printing" a screen or scraping loses the hierarchical structure, making the print-out no better than exporting the csv from the Enclave Concept Set Browser

### Describe the solution you'd like
A button (?) that, when pressed, exports the current screen to a csv, with the hierarchy maintained

### Describe alternatives you've considered
"Print" from the browse file menu, selected everything on the screen, copying, and pasting

**Comment by mtj0712** [comment]
@Sigfried I made a pull request #393 with cset_comparison_new_info_panel branch. I tried to incorporate the requests Harold made above, but I'm not sure if I did it properly... Please review and tell me if anything should be done.

**Comment by joeflack4** [comment]
Just copied over information from duplicate #377 and placed in the body of this issue. Also added Harold's 4 sub-tasks as a checkbox list in the body.

**Comment by mtj0712** [comment]
This issue is solved by pull request #393. Closing the issue.

**Comment by joeflack4** [comment]
Looks great guys!
<img width="1236" alt="Screen Shot 2023-06-16 at 5 10 31 PM" src="https://github.com/jhu-bids/TermHub/assets/13045020/2d600fbd-0136-41a0-917a-fa5fb2f3bf2b">
