### ISSUE TITLE
DB refresh: Temporarily deactivated / broken due to `csets_to_ignore`

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#406]
## Overview
Recently, `public.csets_to_ignore` was added as a view, derived from `all_csets`. This breaks the refresh pipeline because it creates a new `all_csets`, and goes to delete the old one but can't because of this new dependency. 

## Error message
`sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table all_csets_old because other objects depend on it
[74](https://github.com/jhu-bids/TermHub/actions/runs/5305446917/jobs/9602408738#step:8:75)DETAIL:  view public.csets_to_ignore depends on table all_csets_old
[75](https://github.com/jhu-bids/TermHub/actions/runs/5305446917/jobs/9602408738#step:8:76)HINT:  Use DROP ... CASCADE to drop the dependent objects too`

Full github action log: https://github.com/jhu-bids/TermHub/actions/runs/5305446917/jobs/9602408738

## Sub-task list
- [x] 1. @Sigfried: Create DDL
- [x] 2. @Sigfried: Can we change schema of this table from `public` to `n3c`?
- [x] 3. Update script to include `csets_to_ignore`
- [x] 4. Reactivate DB refresh action

### 1. Create DDL
The DDL for `all_csets` is `ddl-9-all_csets.jinja.sql`. So it should come after that. The integer after `ddl-` represents the order in which the DDL will run during (a) a refresh (only runs a subset of these files), or (b) `initialize()` (runs all of these files). There are currently 13 steps in total. If you want to run the DDL for `csets_to_ignore` directly after `all_csets`, you'll need to rename the other files to renumber them. Or, it might be well enough just to insert it at the end as step 14.

### 3. Update script to include `csets_to_ignore`
In `backend/db/utils.py`, in `refresh_termhub_core_cset_derived_tables()`, I've already commented out `'csets_to_ignore',` on two lines. I believe that after the DDL file is in place, these can simply be uncommented, and the refresh should work.

### 4. Reactivate DB refresh action
In `.github/workflows/refresh_db.yml`, lines 3 and 4 (`schedule:`, `- cron: ...`) simply need to be uncommented.

**Comment by joeflack4** [comment]
Handled by: https://github.com/jhu-bids/TermHub/commit/4895b577758636a8a6895fddfe21ed2445e6934f

Also includes table `concept_ids_by_codeset_id`
