### ISSUE TITLE
Tests: GH action: backend

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#409]
## Overview
In order to prevent things from breaking, it would be good to run our unit tests more frequently / in automated fashion.

## Sub-task list
- [x] 1. Create the basic action
- [x] 2. When to run
- [x] 3. What to run
- [x] 4. Test [passing/failing badge](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge)
- [x] 5. Get it to pass (opted to do this in a separate PR)

### 2. When to run
- Daily?
- On pull requests
- On push to dev?

### 3. What to run
- Simple/all backend tests
- Simple/all frontend tests?

### 5. Get it to pass
Right now the tests are a mess. Many old and not up-to-date with recent changes and will probably fail. Others half finished. Need to:
- [ ] i. Deactivate any tests that aren't ready / updated enough to run (fixing these is a [separate issue](https://github.com/jhu-bids/TermHub/issues/353)). Probably best way to do this is through a decorator like `@dontrun` or something (OAK does this so I can borrow their code), or a config variable, something like `RUN_UNFINISHED_TESTS`, and could have an if statement that checks that at the beginning of the test.
- [ ] ii. Fix any tests that are failing but can be fixed quickly
