### ISSUE TITLE
`--counts-docs` daily/weekly aggregation

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#418]
## Overview
@hugwuoke Remember when we were on call earlier and we were looking at the [counts/deltas tables in the docs](https://github.com/jhu-bids/TermHub/blob/develop/docs/backend/db/analysis.md) and remarking at how they are soon going to explode due to the increasing refresh rate? I'd like you to go ahead and make some preliminary changes. We may iterate on these and possibly remove the older versions of the tables altogether and replace w/ these new ones.

## Sub-task list
- [x] 1. Once per day

### 1. Once per day
- [x] Add two new table sections, "Deltas over time, 1x/day", and "Counts over time, 1x/day".
- [x] Remove the "COMMENTS" row from these tables.
- [x] Make it so that the table shows a maximum of 1 column per day. 
  - [x] For counts, it should use the counts for the last entry that day. 
  - [x] For deltas, it should show the net total. E.g. if there were 3 runs in a day, and one of them was -10 rows, then +10, and another +10, the delta should be '20' for that day.

## Possible future tasks
I'm thinking about maybe adding some of the following. @Sigfried Your input would be appreciated if you think there's value in:
- Doing 1x/week tables in addition to / instead of 1x/day
- Comments: Keeping comments in the 1x/day 1x/week tables, but filtering out all comments for (i) automated refreshes, or (ii) users pushing the button, and only showing all comments made during that period that were "deliberate comments" from some special process. E.g. if we refresh 24 times/day and we're showing a table of weekly aggregation, and during 2 days that week, we ran a manual `--counts-update` with notes "Fixed a corrupted table" and "Added a new table", the value in the `COMMENTS` row for that given weekly column would be `"Fixed a corrupted table", "Added a new table"`.
- Line chart for counts. Either 1 line per table, or only 1 single line for the grand total. X axis for day/week. Y axis for count.
- Bar chart for deltas. X axis for day/week. Y axis for delta. Something like this:
![2D bar chart with postive and negative values each assigned its own color](https://github.com/jhu-bids/TermHub/assets/13045020/6dff0501-1b92-40b8-b11c-b1356fc366f4)

**Comment by joeflack4** [comment]
Chris (**cgchute**), if you see this, I accidentally tagged you.

**Comment by joeflack4** [comment]
Went with just daily aggregation now; not opting for any of the "possible future tasks" at this time.
