### ISSUE TITLE
DB refresh: effective delay experiment 1

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#432]
## Overview
We want to do a test case of how long it takes after making a code set in the enclave before it appears in TermHub. Our results won't mean that the delay of all created code sets will take exactly this long, but it will give is a rough idea.

## Sub-task list
- [ ] 1. Create a code set
- [ ] 2. Wait 20 minutes _(estimated minimum time should take to appear)_
- [ ] 3. Find out how long it takes to appear in TermHub

### 1. Create a code set
Create a code set in the enclave. Make one with a lot of concept members, like 2,000+. In order to do this, you can find a single concept with a few thousand descendants, and use that in your code set as a single expression item. Medication concepts are a common case. You can find such a concept by browsing code/concept sets that have a few thousand members.

### 3. Find out how long it takes to appear in TermHub
Open TermHub and clear the cache using the button in the "Help / About" page. Go to to the "Cset search" page and see if it appears in the list. Come back 1-2 minutes later, repeating this process until it appears.

For lucky timings, it could take 20 minutes for it to appear. If we get unlucky with what the timing of the enclave's and TermHub's routine refreshes, this could take up to 45 minutes or slightly more. to appear. Well, that's if Amin is correct and there is no delay between when code sets appear in the API and when its concept members appear. If he's wrong, it could take up to 65 minutes.

## Related
- #433

**Comment by joeflack4** [comment]
@hugwuoke Closing this issue in favor of #433 in order to just keep everything together. This one has also been deprioritized. I think Siggie prefers to do another of the tests instead of this one, and may be doing / have already done it themselves.
