### ISSUE TITLE
DB refresh: button: Call backend directly

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#442]
## Overview
Some rudimentary server setups are single threaded and cannot handle long tasks without blocking other requests. I doubt that is the case with our server. So, when designing the button, we should have probably tried calling the backend directly, rather than calling the action. We should make this change now and verify that we can continue using the app normally, while the refresh is running after clicking the button.

## Sub-tasks
- [x] 1. Call backend directly instead of GH action
- [x] 2. While working on this, write some logic such that if the refresh doesn't find any new data when it refreshes, it returns, rather than remaking the derived tables
- [x] 3. Check that with the changes made to '1', you can still use the app normally. If there's no data, it'll probably finish the refresh super fast, so you can probably set a breakpoint in the refresh function so that it pauses there, and then you can try to open different tabs and do stuff in TermHub to check if it's not locked up by the refresh.

## Ideally depends on
- #395

## Needs testing
The code is already in place, see [About.js line 90](https://github.com/jhu-bids/TermHub/blob/238aac874a2120fc2bd12e646b6e98fafb1d6b35/frontend/src/pages/AboutPage.js#L90-L97)

**Comment by joeflack4** [comment]
@hugwuoke If I can help get your local setup working correctly, that would be the best thing before working on this, but it is not entirely necessary. Basically, the route that you worked on to call the GitHub action would be changed so that it instead calls the function in `refresh.py` directly.
