### ISSUE TITLE
DB refresh: Vocab and counts tables

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#447]
## Overview
Create a script and make a GitHub action that refreshes the vocab and counts tables weekly using the datasets API.

## Major tasks
- [x] Initial implementation
The implementation I'm currently thinking would remake the tables like we do with the derived tables in the DB refresh. Rather than drop them and recreate the, we would create a new table with the `_new` suffix, then rename the table we're replacing w/ a `_old` suffix, remove the `_new` suffix from the new table so that it is now the active table, and finally delete the old one with the `_old` suffix.
- [x] Fixes to get GitHub action to work.
  - #519
  - #626
- [x] Ensure indexes are created #633
- [x] Ensure PKs are set #632

## Questions / considerations
- [x] 1. What day/time is best to run this on? When does the enclave update these tables?
@joeflack4: Approximately weekly, but I don't know if it's on a particular day. Get the latest update with`enclave_wrangler.datasets:get_last_vocab_update()`. Currently returns `'2023-07-22T15:28:09.766Z'`.
- [ ] 2. Performance: Similar to what #448 intends w/ the derived tables, perhaps we want to update tables rather than remake them? E.g. (i) _deletes_: when we fetch new datasets, remove any rows from the corresponding DB table if they don't exist in the newly downloaded dataset (indicating that they're delated, and (ii) _creates_: add any new rows in the new dataset if they don't exist in the corresponding table. And then there's also (iii) _updates_: is it possible for rows/records to be updated?

**Comment by joeflack4** [comment]
Closing #340 as I think it's a duplicate of this. Here were the contents:

## Overview
**[OMOP vocab tables](https://ohdsi.github.io/CommonDataModel/cdm60.html#Vocabulary_Tables)**:
- `concept`
- `concept_relationship`
- `relationship`
- `concept_ancestor`

**Enclave derived tables** that are updated when it updates OMOP vocab tables:
- `concept_set_count_clamped`
- `deidentified_term_usage_by_domain_clamped`

**TermHub derived tables** that depend on these tables
- `concept_relationship_plus` (from `concept_relationship`)
- `concepts_with_counts` (from `deidentified_term_usage_by_domain_clamped`)

These get updated no more than a few times a year, if even.

This will probably involve using the datasets API to get updates.

**Comment by Sigfried** [comment]
There's a way to tell when a dataset on the enclave has been updated. That would tell us when this needs to run. I forget how to do it. When you're ready to work on this, let me know and I'll try to figure it out again.

**Comment by Sigfried** [comment]
Added answer to description above:

  - Approximately weekly, but I don't know if it's on a particular day. Get the latest update with`enclave_wrangler.datasets:get_last_vocab_update()`. Currently returns `'2023-07-22T15:28:09.766Z'`.

**Comment by joeflack4** [comment]
Re-opening because actions are still broken. Hopefully fixed soon.

**Comment by joeflack4** [comment]
Complete
