### ISSUE TITLE
Grouping: UI errors: Stephanie, July 19

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#489]
## Overview
Just wanting to make a wrapper issue around several issues that Stephanie is experiencing today, while trying to analyze the following csets in this URL: https://icy-ground-0416a040f.2.azurestaticapps.net/OMOPConceptSets?codeset_ids=417730759&codeset_ids=423850600&codeset_ids=966671711&codeset_ids=577774492

## Sub-issues
- [x] 1. Clicking "load concept sets" after already loaded: https://github.com/jhu-bids/TermHub/issues/488
- [x] 2. Sometimes cset comparison page doesn't load: https://github.com/jhu-bids/TermHub/issues/490
- [ ] 3. Observed 0 patient/records counts for some csets: https://github.com/jhu-bids/TermHub/issues/491
- [x] 4. Can't select 1 concept set (`[N3C] Sulfonylureas(v13)`) from cset search _(Joe couldn't replicate)_
- [x] 5. Could not load selected csets _(Joe couldn't replicate; I think Stephanie meant couldn't load comparison page)_

## Additional information
I observed no errors in the backend logs.

**Comment by joeflack4** [comment]
Closing because everything on here except 1 issue is now complete. So for that issue, just refer to the issue itself:
- #491
