### ISSUE TITLE
Bug: "Fetch failures - excessive members/items"

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#518]
## Overview
After a recent refresh, I checked the `fetch_audit` table and noticed cset `938394329` with message `Failed after 28000 members.`.

## Sub-task list
- [ ] 1. Script fails w/ HTTP error 406 ([log](https://github.com/jhu-bids/TermHub/actions/runs/5861503269/job/15891704377))
- [ ] 2. Need to successfully fetch `938394329` after '1' fixed.
- [ ] 3. Refresh fails to initiate GH action for "Fetch failures - excessive members/items"
