### ISSUE TITLE
Not all csets are being fetched

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#521]
### Background
Recently, I did some manual testing and found that around 25% of new concept sets were not being fetched using the DB refresh / objects API. We've [implemented a workaround](https://github.com/jhu-bids/TermHub/pull/507#discussion_r1290832148) that will hopefully work, where we add a buffer period of 2 days to every refresh, as opposed to just fetching from the timestamp of when the last DB refresh completed.

We don't know the cause of this issue, whether it's a bug in TermHub, or if maybe sometimes new concept sets are not appearing in the enclave API.

### General task
We probably don't have time to do this testing unless the workaround fails. But it would also be nice to figure out what is going on that is causing this issue. Ideally if we can fix it in a more straightforward way that would be ideal.

### Sub-task list
- [x] 1. Unit test to identify missing csets
- [x] 2. Import missing csets into DB manually
- [x] 3. GH action to check for missing csets
- [x] 4. In TermHub but not in Enclave (not done but moved to #571)
  - [x] 4.1. Analyze: why? _(most are drafts)_
  - [x] 4.2. #571
- [x] 5. Fix DB reset? Stuff from 2022 was missing (not done but moved to #399)
- [x] 6. Find answer? Why counts [stopped increasing after 8/26](https://github.com/jhu-bids/TermHub/blob/missing-csets-test/docs/backend/db/analysis.md) (probably caused by #574)

#### 4. Analyze: In TermHub but not in Enclave
<details><summary>Details</summary>
<p>

[Siggie wrote](https://cd2h.slack.com/archives/C034EG5ESU9/p1694707442165729):
There seem to be 228 code sets that appear in the code set table but don't show up in the OMOPConceptSet API (and, for the few I've tested, in the concept set browser either). 
[@amin](https://cd2h.slack.com/team/U0126590W0Z) or [@Maya Choudhury](https://cd2h.slack.com/team/U01AHJSHCFK), you have any idea what's going on with these? I made a [code workbook](https://unite.nih.gov/workspace/vector/view/ri.vector.main.workbook.a0dd4705-cf28-4312-8680-56ee2d7842ad?branch=master) to show which ones they are. The list of codeset_ids came from a list of 330 codeset_ids in the TermHub database that don't show up in the API.

Joe: I see they all show as non-archived as well. I checked one, and it also wasn't a draft

</p>
</details>

**Comment by joeflack4** [comment]
Siggie's idea: make objects request for `OMOPConceptSet` (or datasets API `code_sets`), to fetch all. extract `codeset_id`s, and compare to what's in the database.

**Comment by Sigfried** [comment]
I wrote the basic test in https://github.com/jhu-bids/TermHub/blob/develop/test/test_database.py, but it’s failing, so we need to dig into what’s going wrong. 

What I’ve discovered so far is that most of the code_sets missing from the database are drafts. But if `make_objects_request('OMOPConceptSet')` is getting these csets, then the db-refresh should be loading them, right?

Then we need to look into the small number that are missing but not drafts, and the csets that appear in the database but not in the enclave.

**Comment by Sigfried** [comment]
Working with Hope on figuring out what's wrong:

  1) was counting archived csets as missing, but we don't download those. fixed the test to ignore the archived ones
  2) still have 81 missing, 75 are drafts, 6 are not
  3) starting with nondrafts, ['[N3C] Sulfonylureas (v4)'](https://unite.nih.gov/workspace/hubble/objects/ri.phonograph2-objects.main.object.62518504-5ea5-4c93-a29f-218f869d031a) is missing, don't know why.

**Comment by joeflack4** [comment]
Regarding (3), hmm, hard to say. My guess is that, since it was created on _Jul 13, 2023, 2:18 PM_, perhaps that has something to do with it. That was right around when we did the last "database reset". Then, in early August, we did a fetch 30 days in the past. I had thought that it would have fetched everything since the last reset, but maybe it missed a a couple days, including the 13th, when this one was created? It's just a guess.

I would imagine we are able to fetch it now, either using the `since` param, or requesting it by ID. If that's not the case, we should investigate further. But if it and the other csets are indeed fetchable now, I think what we need to do is simply import them manually now, and then implement some kind of automated way to import them, whether that mean (a) changing the 2 day buffer on the db refresh, or (b) implementing some other kind of QC check, perhaps a unit test.

**Comment by joeflack4** [comment]
Analysis update.

List of missing csets slightly higher today, I'm guessing because some new csets were created today and the refresh has not run yet.

Here's a list of stuff missing from TermHub, though I'm going to try to import this all now. Will be providing updates in: 
- #555
<details><summary>In Enclave missing from TermHub</summary>
<p>

972115456
236721924
301528581
782301199
14850578
566641682
826385940
873831446
288822550
253995545
151415578
986559005
136730142
109571358
664055583
39246624
308452648
844665905
734131249
628871985
512865075
746279477
671112503
56536120
567722555
48968767
116426304
400934463
667054402
883835982
124056655
54804053
763433302
731731287
151401817
165676891
711397723
42627932
697379937
651669858
302441827
853448041
173946731
499789933
554076020
428026745
438155132
689083517
408237440
995809925
506813574
850067845
808568710
638871434
629368715
932060044
328885916
607095196
734613916
462987423
832255135
786650526
357499298
907122598
986944935
692842918
33255083
718156972
856402347
430262190
646869938
14931131
992183739
942447295
540749759
280318148
299982032
462280913
929770715
27777759
154903008
538834400
950515429
338173671
153135848
605175528
275212008
999577577
924525546
120648433
561150200
317712124
620657662

</p>
</details> 

<details><summary>In TermHub missing from enclave</summary>
<p>

53641216
885041152
668178434
3
4
5
458893315
1000001549
409696270
824058893
710933521
949350422
627015703
607439896
688989212
8310817
579550245
652960807
1000067113
658192432
460306483
651843635
530289717
1000070201
258391101
740634689
248377411
847880260
667263045
880838727
409576520
530611274
20639828
679955543
669318233
192792668
637231200
496869473
696866914
434548836
7244900
1000006757
15975526
238993514
696927341
664225905
605209714
984632439
24367228
382340224
75878534
142742664
88251529
631768203
1000077454
356028559
87387281
191885458
597464210
524093590
119302297
460618909
159886497
751760546
1000012963
56844454
326423718
432405674
179437741
687120559
359649466
761438398
941759680
1000050882
1000072407
1000040664
430300389
206324966
365612264
201208045
802660592
831171825
273388789
129900794
826644735
804007167
166655234
304229636
711610630
549708040
693341448
135384329
601154829
910996757
681154838
347670809
260640026
104675613
64167201
642523426
1000007970
792804656
275689782
935841087
99571011
1000009030
235672903
986206537
753263945
16234831
1000034639
39366993
590769488
756561238
282417496
877257055
919183712
721309025
818482530
433529188
951057765
216237418
402168171
879711596
314327414
865922424
614015354
17341820
854831485
282474878
558889344
403248516
56073617
273070485
815113623
464829850
641510816
132298144
622061987
31473061
47428014
984682927
967144879
372913584
868253106
236486068
394033589
492445111
345707969
526308803
991869380
963850703
352033239
894699992
949146072
628829657
1000098272
853589472
525353444
803154407
800684528
885936626
573259256
58437116
540008957
135046652
750419452
638189053
768934402
612841987
334170631
833216008
775551497
606831116
531054092
244330007
943400474
299887131
1000001050
303385117
894148124
383753758
489185830
1000087082
501391916
1000032818
341023289
896499269
988516943
398765648
986794577
762387029
629561942
387938906
270077533
988958304
611206754
426694246
442944105
728184425
270905965
726909556
648475253
534085240
1000005251
213053062
11181707
88938126
1000083089
552271509
573765270
994822810
344101538
1000005289
372372139
857065132
304286381
679849648
719834803
457300660
1000079028
860860086
586532535
1000094394
705844923
776638143
592517824
896243393
763274950
216976071
697160393
743410378
865116874
836802253
217270990
893724367
768765647
472022737
556935890
222024407
45952728
523086556
951218910
137459423
139515617
172935906
301584099
918530799
952464113
961844978
322718452
302593795
925786884
575958789
804808454
345145095
600934155
816361235
1000071956
1049370
908112670
107340576
52622112
736492325
966769447
698133288
548643625
862118698
32495403
902895405
801408815
285590322
1000059701
516454198
377841471
637513538
903235397
261461833
828064586
426161993
143192912
222040920
528661350
373085033
981622639
176612210
233202548
942146424
647864184
796120959
874562435
935686019
426891141
30411659
176263053
1000017807
686341008
413526936
625433503
460948395
693272502
56341432
51433400
798718908
267229117
689422271
1742786
61107144
440008649
276348877
473709518
771800015
514709454
485521360
72963026
996052950
955846615
597821400
532457430
326195161
952137691
555633631
18860002
956347363
265563108
112182256
770950132
176841716
27512823
833756157

</p>
</details>

**Comment by joeflack4** [comment]
After importing those missing csets, test now passing:

```
(termhub) python -m unittest test.test_database.TestDatabaseCurrent.test_all_enclave_csets_in_termhub; beep
.
----------------------------------------------------------------------
Ran 1 test in 17.671s

OK
```

**Comment by joeflack4** [comment]
Added some more sub-tasks to the OP, including "Find answer? Why counts [stopped increasing after 8/26](https://github.com/jhu-bids/TermHub/blob/missing-csets-test/docs/backend/db/analysis.md)"

**Comment by joeflack4** [comment]
Re: " 4. Analyze: In TermHub but not in Enclave"
[Siggie wrote](https://cd2h.slack.com/archives/C034EG5ESU9/p1694720288607339?thread_ts=1694707442.165729&cid=C034EG5ESU9):
> Ok, so nevermind, Palantir folks. Sorry, the problem is on our end.

@Sigfried Lemme know more about that / either here or at meeting.

**Comment by Sigfried** [comment]
I looked at [several of the csets](http://localhost:3000/OMOPConceptSets?codeset_ids=53641216&codeset_ids=885041152&codeset_ids=668178434&codeset_ids=3&codeset_ids=4&codeset_ids=5&codeset_ids=458893315&codeset_ids=1000001549&codeset_ids=409696270&codeset_ids=824058893&codeset_ids=710933521&codeset_ids=949350422&codeset_ids=627015703&codeset_ids=607439896&codeset_ids=688989212&codeset_ids=8310817) appearing in termhub and not in enclave. 

A bunch of them are drafts. We can look at those later because I'm still not sure what drafts we're supposed to have access to. 

Maybe they got into the database a long time ago and we just need to delete them and they won't come back.

**Comment by joeflack4** [comment]
I suppose that makes sense that some of them are drafts. I suppose this will happen again in the future (as we fetch drafts, and then they are discarded), until I get to completing #398. It's good that we have a unit test for this.
