### ISSUE TITLE
OHDSI Symposium Poster

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#567]
## Overview
OHDSI symposium poster.

## Sub-tasks
- [x] Writing of abstract @Sigfried 
- [x] Editing / refining of abstract (if needed) @joeflack4 
- [x] Poster finalization @joeflack4  @Sigfried 
- [ ] Attendance and poster presentation @joeflack4 @oct20-22
