### ISSUE TITLE
Deploy usage statistics branch, etc

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#568]
## Overview
Siggie was in the middle of trying to deploy this, but some issues came up and I am completing this task.

## Sub-tasks
- [x] 1. Cursory investigation of [new deploy error](https://github.com/jhu-bids/TermHub/actions/runs/6241494677/job/16943780124), and update infra team
- [x] 2. Reset `missing-csets-test` branch back to what it was when I last worked on it
- [x] 3. Create new `usage-stats` branch off of the last stable commit we deployed
The code for this will be moved over from the new commits siggie made to `missing-csets-test`

**Comment by joeflack4** [comment]
I branched created a new PR #569, adding usage statistics, branching off of the last successful deployment commit: `1cc2688ba421edba3de11c0736c4625165701029`

I was able to successfully redeploy from [temporary branch `deployment-2023-09-07-branch`](https://github.com/jhu-bids/TermHub/tree/deployment-2023-09-07-branch), before branching off and creating this `usage-statistics` branch.

I also kept a tag for this. I do that sometimes for deployments: https://github.com/jhu-bids/TermHub/tree/deployment-2023-09-07

**Comment by joeflack4** [comment]
In regards to (1), I looked into it and found a possible cause. See: #570
