### ISSUE TITLE
Prep: Oct 8th Demo

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#572]
## Overview
_Siggie wrote:_
> Shawn just mentioned (we're on office hours) that on Sunday, Oct 8 they're (Anita, Shawn, not sure who else) putting on a demo of N3C for journalists and would like me (or someone) to present TermHub. Very exciting, and, yikes! We need to do some serious testing (and fixing) before then

The following might be some good preparation steps.

## Sub-tasks
- [ ] 1. Write a script for them to follow?
- [ ] 2. Do some manual testing to identify priority bug / UX fixes
- [ ] 3. Choose some stability things to work on
  - [ ] Stuff found in step (2)
  - [ ] Other stuff currently on board
- [ ] 4. Do that stuff
