### ISSUE TITLE
Bug: "0 members fetch failures" GH action broken

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#585]
## Overview
The GitHub action for "Resolve fetch failures: 0 members" just ran and failed in a way I haven't seen before.

## Sub-tasks
- [ ] 1. Fix the bug.
- [ ] 2. Run `resolve_fetch_failures_0_members.py` manually to import the missing cset.
- [ ] 3. Optional: Check the `fetch_audit` table to make sure the record is marked resolved (it should have a non-null success_datetime)

## Error message
From [the log](https://github.com/jhu-bids/TermHub/actions/runs/6518568212/job/17704124289): 
```
...
Derived tables
 - creating new table/view: cset_members_items...
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(cset_members_items_new, 619116) already exists.
```

## Discussion
It seems to be complaining about a duplicate record / primary key. I'm a little confused because when it creates this table, it should be getting that information from tables which already have the same constraint, so I don't know how a duplicate would have snuck in there.
And also, I'm confused because it seems to say `619116` already exists, which is a single key, but the primary key should be 2 values: codeset ID and concept ID.

For reference: Indexes on `concept_set_members`:
<img width="539" alt="Screen Shot 2023-10-14 at 5 18 06 PM" src="https://github.com/jhu-bids/TermHub/assets/13045020/4624cf62-0623-4b5c-bdf6-06b1ac63b635">

This seems to be the failing case:
<img width="740" alt="Screen Shot 2023-10-14 at 5 21 40 PM" src="https://github.com/jhu-bids/TermHub/assets/13045020/63aacedf-d87b-4c3c-b49b-79c839359e50">

**Comment by joeflack4** [comment]
Looked [into this](https://stackoverflow.com/questions/54351783/duplicate-key-value-violates-unique-constraint-postgres-error-when-trying-to-c). At the moment it looks like things are in parallel. Like 2 actions trying to update derived table at same time.

Need to further improve my method of blocking derived tables recreation if it is already in progress. Somehow this fetch failures action is ignoring the safety check I have in place.

**Comment by joeflack4** [comment]
I would have expected the problem mentioned above to be fixed already by introduction of logic that prevents the derived tables from being refreshed until their current refresh ends.

However I just noticed a bug in this. It was recursively calling itself. And I just fixed it / will be fixing it shortly.

I just got this timeout issue however:
> `RuntimeError: Timed out after waiting 2 hours for other active derived table refresh to complete.`

This is likely caused by Siggie and I developing and the process exiting without marking the status variable `inactive`.

Perhaps I should change this so that if it waits 2-3 hours and nothing has happened, it will simply consider that this is in error, and then proceed with what it needs to do. Then when it ends, it'll set to inactive.

I can also use the same logic I used with the DB refresh where instead of a active/inactive variable, I go with "last request/started" and "last exited".

**Comment by joeflack4** [comment]
I've also noticed that there are 6 cases currently waiting in the DB to be refreshed for `fail-0-members`, and two for `fail-excessive-members` (but that one is not super useful and I think harder to fix).

**Comment by joeflack4** [comment]
I wish I knew why this happened, but I don't. It has resolved itself; there are no outstanding fetch failures and the action is completing successfully, so I'm closing this and we can re-open if it re-arises.
