### ISSUE TITLE
Integrate `OMOPConceptSet.omopVocabVersion`

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#594]
## Overview
The API model for `OMOPConceptSet` just changed.

## Sub-tasks (modified from @joeflack4's comment below)
- [ ] At the very least, add the field for omop vocab version
  - [x] Add to code_sets table
  - [ ] all_csets
  - [x] OMOPConceptSet <==> code_sets mapping
- [ ] It's already in code_sets. Make sure the refresh isn't ignoring this field or other fields.
- [ ] They're going to retroactively adding vocab version to like 2021 sets, and we'll need to re-initialize at that point.
- [ ] The omopconceptset table too
- [ ] Any issues with containers?

## Sub-tasks (old, are these still needed?)
- [ ] 1. Enclave wrangler: (i) Receive data in conformance to new API, and (ii) propagate that data in all the correct places.
- [x] 2. Enclave Wrangler: Send data in conformance to new API (I think we upload via the `OMOPConceptSet` API?)
   - If we don't set the version, it sets it accurately
- [ ] 3. Update DB table(s) w/ any field changes

## Additional details
Screenshot showing field differences between 2 different versions of the same concept set. Fields missing between versions shown with `*`. This does not mean that everything starred is a new field; just newly added in between those versions. 
The only new field is `omopVocabVersion`.
<img width="1316" alt="MicrosoftTeams-image" src="https://github.com/jhu-bids/TermHub/assets/13045020/cc3a20ba-8188-494b-9236-ea47a3353f23">

**Comment by joeflack4** [comment]
At the very least, add the field for omop vocab version. Add to 1 or more database tables.

**Comment by joeflack4** [comment]
It's already in `code_sets`. Make sure the refresh isn't ignoring this field or other fields.

**Comment by joeflack4** [comment]
Where we left off, Siggie believes that they've completed all of these checkboxes, other than that the `all_csets` table doesn't have the new field yet. But we don't need that field in that table yet, or maybe Siggie does. They're running it right now.
