### ISSUE TITLE
Dynamic subtrees (collapsing many lines to one)

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#602]
## Overview
We want TermHub to be more performant, and with large concept sets, this involves only loading part of the concept set at first, and then dynamically increasing what the user sees, probably based on when they click expand/collapse.

## Sub-task list
- [ ] 1. Determine basic algorithms for showing/hiding sub-trees
- [ ] 2. Determine caching strategy
- [ ] 3. Implementation
  - [ ] collapse algorithms
    - pre-collapsing of trees
    - collapsing other parts of tree when user wants to expand other part
  - [ ] expansion algorithms
  - [ ] caching
  - [ ] _allow user to expand more_: than ~2k, either by chunk (e.g. 2k -> 4k), or immediately beneath a node (1 layer or more)
  - [ ] UI
- [ ] 4. QA
  - [ ] i. #639
  - [ ] ii. #640

## Considerations
1. **Concepts in definition can be hidden**: I tend to think of concepts in the definition as being high up in the tree, but that isn't always the case. It is certainly possible that these concepts can be lower and get hidden. I just wonder if this would be counterintuitive and confusing to users.

## Details
**General idea**
We pick a number, say 2,000 as we discussed at 8/24 DL meeting (see analysis & thoughts [here](https://github.com/jhu-bids/TermHub/issues/514#issuecomment-1692647013)). For csets with more members than this number, we start to filter out some sub-trees (descendants of certain concepts), and only render those concepts when the expand (+) icon is clicked.

More recent discussion: https://github.com/jhu-bids/TermHub/issues/514#issuecomment-1724124566

<details><summary>Details</summary>
<p>

Caveat: If we're lucky enough that all the large csets are just medication concept sets, then perhaps _3. Filtering (of RxNorm extension)_ is all we need.

**Options: When to fetch data**
(a) only fetch those concepts/descendants when the user clicks to expand
(b) load them in the background after the initial view has lazy-loaded
(c) both; do 'b', but when the user does 'a', clicking to expand, fetch/expand that first, then continue with 'b'.

**Options: Algo for what sub-trees to hide**
@Sigfried Curious if you've come up against this problem before. @hlehmann17 Any algorithm ideas? Know anyone who's good at this sort of problem?

_a. Hide no concepts until we hit threshold_
Then hide everything past that. This is essentially the same as _1. Pagination_ or _2. On-scroll updates_

_b. Hide sub-trees of certain depth_
For example if the sub-tree is 3+ levels deep, hide it. I see folly in this option.

_c. Hide when a lot of children_
I think 2nd best option after 'e'.
I'm trying to think of how this algorithm would work. This is an interesting problem. I feel like there must be existing or similar known mathematical / computer science problems of this nature with good solutions or heuristics already solved. But I don't even know how I'd google for it. Maybe discuss w/ the sage ChatGPT?

So let's say we have a cset that meets the threshold (e.g. >2k members), I think we'd want to pre-compute this algorithm and cache the "under threshold (<=2k) version" of the cset and load that on initial request.

My initial, probably very poor, idea is this: Recurse the whole tree. For each iteration, count how many children a node has. Record that in a dictionary of `{CONCEPT_ID: N_CHILDREN}`. Then, sort by `N_CHILDREN`. See if we can then somehow do a kind of [Pareto principle](https://en.wikipedia.org/wiki/Pareto_principle), where we take like the "20% of concepts that have 80% of the children", hide those, then see how many unhidden members we have. If still too many members, repeat until we're under threshold.

Some problems I can see with this: Slow / redundant computing. For example we'll likely end up hiding things within things. We can also easily hide too many members, in which case I guess we do a reverse kind of algorithm to unhide portions until we get to our threshold value.

_d. Hide starting with the leaf nodes up_
As I think through 'c' more, I think maybe this could be easier/better in many ways, but has its own problems.

One problem I see with this one is that there may be some leaf nodes that are not deep. For example, say we have a lot of shallow subtrees. Like maybe we have 100 top-level concepts that have only 1 child each. But then we have a handful of other concepts that have 1000s of members and are much deeper. Hiding 100 of those leaf nodes doesn't help much, and actually is poor UX because the user would have to click 100 times to expand each of these.

_e. Hide from deepest depths upwards_
I think this is the best one, and also the most intuitive.

We hide the deepest layers, one at a time, until the unhidden part of the tree is under threshold. If removing a layer removed too much, we can use an algorithm to unhide parts of it until we're at threshold.

By a 'layer', I mean a common depth level across all subtrees. Say for example we have a subtree with 3 starting branches. 2 of them are 7 levels deep, and one of the is 5 deep. The first iteration of the hiding algorithm would remove layer/level 7. So the state of our tree after that would be 2 good 6 level deep trees, and one 5 levels deep.

Before executing the algorithm that hides layers, we'd have to first take inventory such as all concepts and how deep they are; a dictionary of `{CONCEPT_ID: DEPTH}`. Another useful variation would be `{CONCEPT_ID: {'depth': DEPTH, 'n_descendants': N}`; we would be using `n_descendants` later.

Then, we would invert this structure, `{DEPTH: [CONCEPT_IDs]`. At this point, we could begin removing layers 1 at a time as previously described.

Unhiding after hiding too many
After iterating 1+ times, we will be under threshold. It's unlikely we'd hit the threshold exactly. So almost every time, we'll want to proceed to the next part of the algorithm, where we unhide subtrees at that depth until we're as close to threshold as we can, in order maximize the number of concepts shown on initial load.

<details><summary>Unhiding algorithms</summary>
<p>

a. Binary search style: whole subtrees
We first try to unhide half of the subtrees. If 1/2 was too many, we see how it would do if we'd unhide 1/4. If 1/2 was too few, we'd check for 3/4. And we'd keep proceeding with this until we're left with needing to choose whether to add/hide a single tree. The disadvantage to this is that we'll have whole subtrees that are fully expanded, and many at that depth that are not expanded at all, rather than shallow expansion along the whole depth.

b. `n_descendants`
If we saved `n_descendants` earlier, we could sort by this. Then we could go down the list from the most populous subtrees, and just pick as many as we need to be under threshold. This has same disadvantage as mentioned in 'a'.

c. Binary search style: shallow
This would be like 'a', but instead of saying that we will start by seeing how it would be to fully expand and unhide 1/2 the subtrees, we see what would happen if we unhide a single level of depth for 1/2 of the concepts. The rest of the algorithm would be as 'a'. I think this would have the best result for the user. But I think this would be the hardest one to program.

</p>
</details> 

**UI**
_Slider_: A slider to adjust the threshold. Based on our conversations and [analysis of counts frequencies](https://github.com/jhu-bids/TermHub/issues/514#issuecomment-1692647013) (thanks @tannerzhang), at DL meeting 8/24 we felt that 2,000 would be a good initial default.
_Toggle & confirmation?_: Similar to _3. Filtering (of RxNorm extension)_, we could have a toggle w/ a confirmation dialogue. That way, we could allow the user to have the option to keep the slider setting in a certain position, rather than slide it one way and have to slide it back to the same precise location later. There's also the issue where if they slide it and accidentally release too early, it can start loading too soon, and they'll have to refresh the page.

**Keywords**: Dynamic subtrees, dynamic subgraphs

</p>
</details> 

## Related
- #514
