### ISSUE TITLE
Optimization: Hide pre-set concept types (RxNorm extension)

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#616]
## Overview
**General idea**
Show these csets, but when rendered, hide any RxNorm extension concepts _themselves_ and their children.

<details><summary>Details</summary>
<p>

**UI**
_Toggle_: A toggle somewhere to enable/disable this behavior. Set it to on by default.
_Confirmation_: If you click to toggle off, have a confirmation dialogue box with text like, "This could take n minutes to load, are you sure?", where 'n' could be a static number like '10', or we could figure out dynamically how long it typically is taking to load based on number of concepts.

**Discussion**
I think we want to implement this _in addition_ to one of the other options, assuming that there exist large csets that are not medication csets.

@Sigfried This is Harold's idea from the 8/24 DL meeting. @hlehmann17 Is _RxNorm extension_  the only one or also other vocabulary/domains?

</p>
</details> 

## Sub-tasks
- [x] Implement on frontend: don't display
- [x] iImplement on backend: don't fetch
- [ ] Have hidden RxNorm Ext on backend, but user isn't informed and can't toggle. Fix!
  - By toggling the Hide RxNorm Extension slider off? Should it still report how many concepts are hidden? That will now need to be calculated on server and communicated to front end.
  - They also don't show up when user downloads

## Related
Direct grouping issue:
- #514

**Comment by joeflack4** [comment]
We have a frontend option for this and I think it's on by default. But we also need to change it so that the backend doesn't fetch needless stuff. However, I think the biggest problems we're having is on the frontend, rather than fetching too much data from the backend.
