### ISSUE TITLE
AMIA paper 2024

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#631]
## Overview
This could be a great way to promote TermHub, and a stepping stone towards an OHDSI symposium presentation this year as well.

## Sub-tasks
- [x] Find out what the actual deadline is
- [x] Suggest reviewers
- [x] Write the paper
- [x] Submit by ???
- [ ] Post-submission?
  - [ ] If they reject the paper, figure out where else to publish. If they accept, do some re-writing, and make a slideshow, and present it.

## Additional info
- [Draft document](https://livejohnshopkins-my.sharepoint.com/:w:/g/personal/sgold15_jh_edu/EXbuxwBsb0pPgFfgPYjR6qgBlJ1gmpqsMPYJ3vn6Y_HnYw?e=4%3ApEDbMe&fromShare=true&at=9&CID=d4663c40-1ebe-db59-8cf5-2bc091d45692)

**Comment by joeflack4** [comment]
Siggie said that this may involve the `api_runs` table (`api_call` field). Siggie said this will answer questions like "this many users. used TermHub this many times. stats on what they were doing and how errors occurred", and said "academics / amia really see a great value in validation".

**Comment by joeflack4** [comment]
If they reject the paper, figure out where else to publish. If they accept, do some re-writing, and make a slideshow, and present it.

**Comment by joeflack4** [comment]
I'm not sure if @Sigfried addressed this already, probably not, but if we're able to make edits to the paper, we may want to consider:

Siggie accidentally re-enabled inclusion of a lot of "dev data"--namely, the entries coming from GitHub actions. 

The fix might be as simple as uncommenting out these lines in `stats.py` `run()`, but I'm not sure:
```python
    # TODO: consider filtering out the dev data from the 3am gh actions:
    # df_apiruns_dev0: pd.DataFrame = filter_dev_data(df_apiruns_dev1, verbose)
    # df_w_groups_filtered_dev0: pd.DataFrame = filter_dev_data(df_w_groups_filtered, verbose)
```
