### ISSUE TITLE
Performance optimization: Try recommendations

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#662]
## Overview
I spoke with @vincerubinetti today, and he gave some great recommendations on things to try and help with performance!

## Sub-task list
We should evaluate many / each of these things.
- [ ] 1. lighthouse
- [ ] 2. network/performance/memory tabs
- [ ] 3. react dev tools chrome extension
- [ ] 4. pagination
- [ ] 5. web workers
- [ ] 6. state mgmt
- [ ] 7. test: basic HTML table
- [ ] 8. virtual lists
- [ ] 9. CSS content-visibility

## Related
- #514
