### ISSUE TITLE
QC: Feb 2024 deploy (wrap-up)

### ISSUE THREAD

**Issue by Sigfried** [jhu-bids/TermHub#690]
## Overview
Graph stuff etc needed for next deployment.

## Sub-tasks
- [x] 1. debug `get_missing_in_between_nodes()` @Sigfried 
  - Missing node 17
  - _Joe was originally gonna do but Siggie said they fixed / are fixing._
- [x] 2. refactor concept fetching and filtering @joeflack4 
- [x] 3. return **ALL** edges and metadata to front end @joeflack4 
  _@Sigfried is this done as of Mon feb 5?_
  - [x] and what metadata
     - for all nodes
     - for nodes that are to be shown (front end will ask for more when nodes are expanded)
     - summary data for nodes that are collapsed
- [x] 4. **refactor front end**: to create the indented tree again: [chatgpt idea](https://chat.openai.com/share/8e817f4d-0581-4b07-aefe-acd5e7110de6) which does a dynamic HTML table. can we adapt it for react DataTable? @Sigfried 
  - [x] possibly start by copying in chatgpt code and seeing how that works
  - [x] then decide whether to pull ideas/code from there into our current code or use the new code and add whatever functionality we need to it
  - [ ] will want to give summary info for hidden nodes
  - [ ] will want to autohide depth > n or siblings > m for graphs with nodes > o
- [x] 5. Frontend test against `getIndentedTreeNodes()` in `basic-functions.test.js`
  - May depend on #696
- [x] 6. #667 @Sigfried Is this complete yet?
- [x] 7. Post-deployment QC
- [ ] 8. Post-deployment: GitHub issues
  - [ ] Some stuff from "(4) refactor frontend" was not done. still want to do?

## 7. Post-deployment QC
Make sure #667 fix worked, i.e. these constant calls are going away now:
```
2024-02-05T04:19:45.611201684Z http://termhub-dev.azurewebsites.net/n3c-comparison-rpt
2024-02-05T04:19:45.611259585Z INFO:     169.254.130.3:53418 - "GET /n3c-comparison-rpt HTTP/1.1" 200 OK
2024-02-05T04:20:45.602604827Z http://termhub-dev.azurewebsites.net/n3c-comparison-rpt
2024-02-05T04:20:45.602662128Z INFO:     169.254.130.3:48722 - "GET /n3c-comparison-rpt HTTP/1.1" 200 OK
```

## 8. Post-deployment: GitHub issues
Decide which of these are still worth considering and create 1+ GitHub issues:

### UI related
1. maybe allow user to toggle between initial load of
a. roots
b. roots + items
2. expand more than 1 level at a time
page settings area
maybe like let them say 2k concepts and then we expand that deep
3. show specific concept id / id
where
    - page settings area: search box
    - search box: at the top, next to the buttons
what
    - a. new root?
    - b. unhide everything up to that one

### Testing related
In addition to #696, we also want to add more graph related testing.

<details><summary>Specific csets we want to test</summary>
<p>

1. many small -- neurological (4 IDs) - http://localhost:3000/cset-comparison?codeset_ids=1000002657&codeset_ids=241882304&codeset_ids=488007883&codeset_ids=1000087163
2. malignant cancer (2 IDs)- 
http://localhost:3000/cset-comparison?codeset_ids=585389357&codeset_ids=1000003793
3. just one of the csts in both malignant / neuro
  - malignant cancer: 1000003793
  - neuro: any of them

</p>
</details> 

<details><summary>Specific testings cenarios</summary>
<p>

We want to cover the following types of situations:
- **Big**: Csets / combinations of csets that produce very big graphs
- **Many**:  Combos of many different csets at once
- **N3C comparison** cases
- Specific cset combinations that we think might be error prone / exhibit some kind of edge case(s)?

</p>
</details>

**Comment by joeflack4** [comment]
Wrap up: Check if all checkboxes here done or need new issues.
