### ISSUE TITLE
Grouping: `resolve-fetch-failures-excess-items`

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#754]
## Sub-tasks
- [ ] 1. Fix outstanding issues
  - #499 
  - #518
- [ ] 2. Reactivate cronjob for GH action: `resolve-fetch-failures-excess-items`
- [ ] 3. Ensure this refresh doesn't run more than 1 simultaneous process at a time.
  - This may need to come before reactivation. I can use the same solution I have for the DB refresh. Have a DB variable in `manage`, and if it is running (set to `True`), then the secondary action simply exits.
  - The reason fixing this should be a priority is because the refresh runs every 20 min, so this could / will be kicked off every 20 min, and it may well take longer than 20 minutes to resolve even a single fetch failure for such cases.
