### ISSUE TITLE
Add concepts: Search: Include UI in a single table (adding/removing)

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#788]
## Overview
Originally wrote:
> **Concept search: Include UI in a single table (adding/removing)**
> I can't see the UI right now, but I think what's happening is that when we add a searched concept, it gets filtered out of the search table.

What I think I meant _(I'm not sure; I don't see the UI in front of me right now)_:
Bug: When a concept from the search results table is selected by the user to be added, it disappears from the table.

## Sub-tasks
Change the behavior to:
- [ ] Keep them in the table; don't filter out
- [ ] Apply a light grey background color to the row
- [ ] Disable the 'add' checkbox for the row

### Alternative implementations
Could have a second table below the first that shows concepts added.

**Comment by Sigfried** [comment]
I don't remember why I thought that made sense. It makes it hard for user to know which concepts they've already added. Or was that all in combination with a table below of concepts added?

**Comment by joeflack4** [comment]
I like that suggestion, but that would take more time to implement I think, so let's go with the one we decided; whatever is easier.

Also, I think what yous said is that you did not intentionally mean for selected/added concepts to be removed from the search table; that it was a bug.

**Comment by Sigfried** [comment]
I think the way it works now is fine. Now that the terrible performance is fixed.
