### ISSUE TITLE
TermHub: Deployment updates

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#80]
## Tasks
- [x] 1. Figure out commands needed to deploy.
- [x] 2. Add them as commands in `makefile`
- [x] 3. Deploy current state of app
- [ ] 4. Further touch-ups

### 3. Deploy current state of app
- [x] 3.1. set env
  - b. set in azure portal (sergey recommend)
  - a. github actions: possible?
    - read from ENV_FILE secret:
      - I created 2 environmental variables for ENV_FILE. now I just need to figure out how to read and pass at least one of them
        - 1 is a repository secret named ENV_FILE
        - 1 is a environment secret named ENV_FILE
      - https://github.com/jhu-bids/TermHub/settings/secrets/actions
    - create .env file from secret:
      "      - name: 'Create env file'
              run: |
                echo "${{ secrets.ENV_FILE }}" > .env"
      - https://stackoverflow.com/questions/60176044/how-do-i-use-an-env-file-with-github-actions
- [x] 3.2. ensure actions work: https://github.com/jhu-bids/TermHub/actions/
- [x] 3.3. check: does the app work now?
  - resource group (frontend, backend, subscription)
    - https://portal.azure.com/#@live.johnshopkins.edu/resource/subscriptions/fe24df19-d251-4821-9a6f-f037c93d7e47/resourceGroups/JH-TERMHUB-WEBAPP-RG/overview
  - frontend: app url: https://purple-plant-0f4023d0f.2.azurestaticapps.net/
  - frontend: azure portal
    - https://portal.azure.com/#@live.johnshopkins.edu/resource/subscriptions/fe24df19-d251-4821-9a6f-f037c93d7e47/resourceGroups/JH-TERMHUB-WEBAPP-RG/providers/Microsoft.Web/staticSites/termhub/staticsite
  - backend: azure portal
    - https://portal.azure.com/#@live.johnshopkins.edu/resource/subscriptions/fe24df19-d251-4821-9a6f-f037c93d7e47/resourceGroups/JH-TERMHUB-WEBAPP-RG/providers/Microsoft.Web/sites/termhub/appServices
  - backend: app url: ???

### 4. Eventually, clear up all warnings, and update CI flag
- [ ] 4.1 Eventually, clear up all warnings, and update CI flag
In `frontend/package.json`, change this line `    "build": "CI=false && react-scripts build",` to this `    "build": "react-scripts build",`.
- [x] 4.2. deactivate: `<ReactQueryDevtools ...>` (not necessary)
I think this is in `app.js` or `index.js`. This is what shows the little flower at the bottom left of the screen, and caches requests. Will this be deactivated automatically when built, or do we have to set an if/else to render this only when not in production env?

**Comment by Sigfried** [comment]
@joeflack4 What is this about? Still needed?

**Comment by joeflack4** [comment]
@Sigfried Oh this is just standard deployment so that TermHub is web accessible. Still would need to update the S3 and Heroku deployments for this, as well as write some makefile commands (just as an easy CLI) to handle the deployment.

**Comment by joeflack4** [comment]
Waiting on JHU team

**Comment by Sigfried** [comment]
@joeflack4, can you update this issue? How close are we to done with it?

**Comment by joeflack4** [comment]
Only remaining thing here is 4.1, but I'm not actually sure if it is an issue at all. I don't remember why we added the `CI=false` flag, but I know it was something we felt we needed to add when we were setting npm and node versions.
