### ISSUE TITLE
Fix: `test_resolve_fetch_failures_excess_items()`

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#829]
## Overview
`test_resolve_fetch_failures_excess_items()` fails sometimes, but I don't know why. For now I have deactivated the test, as this feature is not important; it's an extremely rare case. I think it's only happened once, and this was on a test cset that we created.

## Error messages
Same errs log, different dates/runs:
- [1](https://github.com/jhu-bids/TermHub/actions/runs/9727456741/job/26847028552)
- [2](https://github.com/jhu-bids/TermHub/actions/runs/9823986797/job/27122473584)

## Sub-tasks
- [ ] Fix errors
  - These things only seem to happen together.
  - [ ] `resolve_fetch_failures_excess_items()` `IndexError`
  - [ ] `TestBackendResolveFetchFailures. tearDownClass()` `AssertionError`
- [ ] Reactivate unit test
