### ISSUE TITLE
Refactor: Enclave endpoints via SDK

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#845]
## Overview
In #837, we added the enclave SDK in order to use OAuth. But it also allows us to use the SDK to call endpoints, rather than the way we've set it up.

It might be nice to use that instead, but it would be a huge refactor, and our current setup works nicely. So this is an extremely low priority.

- [Enclave SDK docs](https://unite.nih.gov/workspace/developer-console/app/ri.third-party-applications.main.application.a4747154-06a6-4282-ad40-b9740234e7b2/docs/guide/getting-started?language=python&packageType=pypi)

Example from docs:
```python
from vshub_sdk import FoundryClient
from vshub_sdk.core.api import ConfidentialClientAuth

auth = ConfidentialClientAuth(
    client_id="e706cf076d6f591ef2f4e2b22006c1cf",
    client_secret="",
    hostname="https://unite.nih.gov/",
    should_refresh=True
)
auth.sign_in_as_service_user()

client = FoundryClient(auth=auth, hostname="https://unite.nih.gov/")

OMOPConceptSetObject = client.ontology.objects.OMOPConceptSet
print(OMOPConceptSetObject.take(1))
```

## Sub-tasks
- [ ] 1. Get them a list of endpoints
  - Send to Amin a list of all the endpoints we need to access. I _think_ this is why Amin asked me to do this at our meeting in 2024/07. I think basically the SDK will only come with endpoint methods that have been configured based on allowed permissions, which they would have to manually set for us based on the list that we send them.
- [ ] 2. Re-install the SDK
  - I think this would need to be done, after they do their setup changes following (1).
- [ ] 3. Refactor & use the SDK
