### ISSUE TITLE
Counts not refreshed since Aug 9

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#882]
## Overview
Normally these refresh weekly, on Thu or Sat I think.

Why has there not been an update in so long? The refresh logs say there's nothing to update.

## Sub-tasks
- [x] Check the "last_updated" date for _all_ counts tables. Normally I just check 1 counts table because they are all supposed to get updated together. Make sure that it really hasn't changed since Aug 9. And make sure that the "last_updated" date is really the same for all tables.
- [ ] Make sure they get refreshed
  - Voc tables updated. So these need to get refreshed
- [ ] Can we set it up to refresh when sources updated?
  - Chris R: _You can set a time-based schedule like cron, but setting it up to build when upstream data gets updated is probably a better use of resources._

**Comment by joeflack4** [comment]
Investigated and indeed, the last time any of them were updated was Aug 8.

**Comment by joeflack4** [comment]
We submitted a ticket: https://unite.nih.gov/workspace/issues-app/issue/ri.issues.main.issue.d32bce68-46f5-407d-9dd8-6ed9bd7a7f91

Chris R explained how to refresh manually if we want / need:
> There are two ways to get those updated, to run the code and buld the table. Comments below, and triaged to Palantir.
> One would be to follow the table to the code that creates it using the "Updated via" link in the column on the left. Once there. you can build it using the hammer icon in a row at the top on the right.
> Another is to schedule a build either via time or updates of inputs via the "Explore Pipeline" on the page with the table in it.  Choose "Explore data lineage" from the pop-up menu, then the hammer here gets you into that functionality. I don't know it well enough to do for someone else.

**Comment by joeflack4** [comment]
the counts hadn't been updated in the enclave; thats why
