### ISSUE TITLE
Enclave bug: Expressions dropped in new version

### ISSUE THREAD

**Issue by joeflack4** [jhu-bids/TermHub#904]
## Background
Sigfried Gold:
>  We are looking at concept set for cardiovascular disease v3 (1000017855) and we made a new version v4 (148977266). Two concept expressions "Fahr's syndrome" and "arteriopathic granular atrophy of cerebral cortex" that were set as "exclude" in V3 are not even listed in V4, but VSHub shows those two as in the vocabulary

## Investigation
Joe looked at one of the concept sets in the enclave. The expressions that were dropped had no effect on the cset. They were all `excluded=true` and `includeDescendants=false` and `includeMapped=false`.

## Possible causes
1. Probably some logic changed in the enclave to where, when new version is made, if the expressions have no effect on the cset, they get dropped.
2. Could be a manifestation of #901

## Sub-tasks
- [ ] 1. Figure out what happened.
- [ ] 2. Figure out: Does anything need to be fixed in the Enclave?
- [ ] 3. Figure out: Does anything need to be fixed about these csets?
